import { useEffect, useState } from 'react';

import { api } from '../api/client.js';
import { formatSeconds } from '../utils/format.js';

/**
 * Triggers the global sync override.
 *
 * The browser sends only the media and a duration; the *shared start instant*
 * is generated by the backend and broadcast as an absolute timestamp, so no
 * client's local clock or message-arrival time can pull the windows apart.
 *
 * @param {{media: Array, activeSync: object|null, disabled: boolean}} props
 */
export function SyncControls({ media, activeSync, disabled }) {
  const [mediaId, setMediaId] = useState('');
  const [durationSeconds, setDurationSeconds] = useState(30);
  const [busy, setBusy] = useState(false);
  const [feedback, setFeedback] = useState(null);

  useEffect(() => {
    if (media.length > 0 && !media.some((m) => String(m.id) === mediaId)) {
      setMediaId(String(media[0].id));
    }
  }, [media, mediaId]);

  const handleSync = async (event) => {
    event.preventDefault();
    setBusy(true);
    setFeedback(null);
    try {
      const created = await api.startSync(Number(mediaId), Number(durationSeconds));
      setFeedback({
        tone: 'success',
        text: `All windows will show ${created.media.name} for ${formatSeconds(durationSeconds)}.`,
      });
    } catch (error) {
      setFeedback({ tone: 'error', text: error.detail ?? error.message });
    } finally {
      setBusy(false);
    }
  };

  const handleCancel = async () => {
    setBusy(true);
    setFeedback(null);
    try {
      await api.cancelSync();
      setFeedback({ tone: 'success', text: 'Sync ended. Windows resumed their own playlists.' });
    } catch (error) {
      setFeedback({ tone: 'error', text: error.detail ?? error.message });
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="panel panel--accent" aria-labelledby="sync-heading">
      <header className="panel__header">
        <h2 id="sync-heading">Global Sync</h2>
        <p className="panel__subtitle">
          Shows one media item on every window at the same instant. Playlists are never modified.
        </p>
      </header>

      <form className="stack" onSubmit={handleSync}>
        <label className="field">
          <span>Select media</span>
          <select
            value={mediaId}
            onChange={(e) => setMediaId(e.target.value)}
            disabled={media.length === 0}
          >
            {media.map((item) => (
              <option key={item.id} value={item.id}>
                {item.name} · {item.type}
              </option>
            ))}
          </select>
        </label>

        <label className="field">
          <span>Sync duration (seconds)</span>
          <input
            type="number"
            min={1}
            max={3600}
            required
            value={durationSeconds}
            onChange={(e) => setDurationSeconds(e.target.value)}
          />
        </label>

        <button
          type="submit"
          className="button button--sync"
          disabled={busy || disabled || media.length === 0}
        >
          {busy ? 'Scheduling…' : 'SYNC ALL WINDOWS'}
        </button>

        {activeSync && (
          <button type="button" className="button button--ghost" onClick={handleCancel} disabled={busy}>
            End sync now
          </button>
        )}
      </form>

      {feedback && (
        <p className={`feedback feedback--${feedback.tone}`} role="status">
          {feedback.text}
        </p>
      )}
    </section>
  );
}
