package service

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/syncstream/media-sequencer/internal/models"
	ws "github.com/syncstream/media-sequencer/internal/websocket"
)

// startSync is a helper that triggers a sync on the first media item of the
// given window and returns the resulting event.
func (h *harness) startSync(t *testing.T, mediaID int64, seconds int) models.SyncEvent {
	t.Helper()
	event, err := h.svc.StartSync(context.Background(), SyncRequest{MediaID: mediaID, DurationSeconds: seconds})
	if err != nil {
		t.Fatalf("start sync: %v", err)
	}
	return event
}

func TestStartSyncSchedulesAFutureSharedStart(t *testing.T) {
	h := newHarness(t)
	window := h.seedWindow(t, "Window 1", 10, 20, 30)
	mediaID := window.Playlist[1].Media.ID

	event := h.startSync(t, mediaID, 30)

	// The start instant is generated by the backend and is slightly in the
	// future, so every client can align to it rather than to message arrival.
	if !event.StartAt.After(h.now) {
		t.Errorf("startAt %s is not after now %s", event.StartAt, h.now)
	}
	if got := event.StartAt.Sub(h.now); got != time.Second {
		t.Errorf("lead time = %s, want 1s", got)
	}
	if got := event.EndAt.Sub(event.StartAt); got != 30*time.Second {
		t.Errorf("sync duration = %s, want 30s", got)
	}
	if event.Media.ID != mediaID {
		t.Errorf("sync media = %d, want %d", event.Media.ID, mediaID)
	}
	if h.events.CountOf(ws.EventSyncStarted) != 1 {
		t.Errorf("expected one SYNC_STARTED broadcast, got %v", h.events.TypesPublished())
	}
}

func TestSyncValidation(t *testing.T) {
	h := newHarness(t)
	ctx := context.Background()
	window := h.seedWindow(t, "Window 1", 10)
	mediaID := window.Playlist[0].Media.ID

	cases := []struct {
		name string
		req  SyncRequest
	}{
		{"zero duration", SyncRequest{MediaID: mediaID, DurationSeconds: 0}},
		{"negative duration", SyncRequest{MediaID: mediaID, DurationSeconds: -5}},
		{"duration beyond the limit", SyncRequest{MediaID: mediaID, DurationSeconds: models.MaxSyncDurationSeconds + 1}},
		{"unknown media", SyncRequest{MediaID: 9999, DurationSeconds: 10}},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			_, err := h.svc.StartSync(ctx, c.req)
			var failure *ValidationFailure
			if !errors.As(err, &failure) {
				t.Fatalf("expected a validation failure, got %v", err)
			}
		})
	}
}

// TestSyncLifecycle walks the three phases the assignment cares about:
// before sync, during sync and after sync.
func TestSyncLifecycle(t *testing.T) {
	h := newHarness(t)
	ctx := context.Background()
	window := h.seedWindow(t, "Window 1", 10, 20, 30)
	syncMedia := window.Playlist[1].Media.ID

	// Before: no override, the window plays its own item.
	if active, _ := h.svc.LiveSync(ctx); active != nil {
		t.Fatal("a sync is active before one was started")
	}
	before, _ := h.svc.CurrentPlayback(ctx, window.ID)
	if before.SyncOverride != nil {
		t.Fatal("current playback reports an override before any sync")
	}

	event := h.startSync(t, syncMedia, 30)

	// Inside the lead-in the override exists but is not yet displayed, which is
	// exactly what lets every client prepare before the shared start instant.
	during, _ := h.svc.CurrentPlayback(ctx, window.ID)
	if during.SyncOverride != nil {
		t.Error("the override should not be displayed during the lead-in")
	}
	if live, _ := h.svc.LiveSync(ctx); live == nil {
		t.Error("a client joining during the lead-in must be able to see the pending sync")
	}

	// During: the override displaces what the window renders.
	h.now = event.StartAt.Add(5 * time.Second)
	mid, _ := h.svc.CurrentPlayback(ctx, window.ID)
	if mid.SyncOverride == nil || mid.SyncOverride.ID != event.ID {
		t.Fatal("the override is not reported while the sync is running")
	}
	if mid.SyncOverride.Media.ID != syncMedia {
		t.Errorf("override media = %d, want %d", mid.SyncOverride.Media.ID, syncMedia)
	}
	// Crucially, the window's own playback state keeps advancing underneath.
	if mid.State == nil {
		t.Fatal("the underlying playlist state stopped during sync")
	}

	// After: the override is gone and playback continues from the cycle clock,
	// landing on exactly the item it would have reached without the sync.
	h.now = event.EndAt
	after, _ := h.svc.CurrentPlayback(ctx, window.ID)
	if after.SyncOverride != nil {
		t.Error("the override outlived its end time")
	}
	if live, _ := h.svc.LiveSync(ctx); live != nil {
		t.Error("a finished sync is still reported as live")
	}

	elapsed := after.ServerTime.Sub(window.CycleAnchor)
	expectedOffset := elapsed.Milliseconds() % 60_000
	if got := after.State.ElapsedInCycleMillis % 60_000; got != expectedOffset {
		t.Errorf("playback did not resume on the cycle clock: offset %d, want %d", got, expectedOffset)
	}
}

// TestSyncDoesNotModifyPlaylists is the invariant the assignment calls out
// explicitly: M2 being synced must not insert M2 into any other playlist.
func TestSyncDoesNotModifyPlaylists(t *testing.T) {
	h := newHarness(t)
	ctx := context.Background()
	w1 := h.seedWindow(t, "Window 1", 10, 20, 30)
	w2 := h.seedWindow(t, "Window 2", 15, 12)
	syncMedia := w1.Playlist[1].Media.ID // "M2", which is not in Window 2

	snapshotBefore, err := h.svc.WindowsWithPlaylists(ctx)
	if err != nil {
		t.Fatalf("snapshot: %v", err)
	}

	event := h.startSync(t, syncMedia, 30)
	h.now = event.StartAt.Add(time.Second)

	snapshotDuring, _ := h.svc.WindowsWithPlaylists(ctx)
	h.now = event.EndAt.Add(time.Second)
	snapshotAfter, _ := h.svc.WindowsWithPlaylists(ctx)

	for _, stage := range []struct {
		name string
		data []models.WindowWithPlaylist
	}{{"during", snapshotDuring}, {"after", snapshotAfter}} {
		if len(stage.data) != len(snapshotBefore) {
			t.Fatalf("%s: window count changed", stage.name)
		}
		for i := range stage.data {
			got, want := stage.data[i], snapshotBefore[i]
			if len(got.Playlist) != len(want.Playlist) {
				t.Fatalf("%s: window %q playlist length changed from %d to %d",
					stage.name, got.Name, len(want.Playlist), len(got.Playlist))
			}
			for j := range got.Playlist {
				if got.Playlist[j].ID != want.Playlist[j].ID || got.Playlist[j].Position != want.Playlist[j].Position {
					t.Errorf("%s: window %q item %d changed", stage.name, got.Name, j)
				}
			}
		}
	}

	// Window 2 must still not contain the synced media anywhere.
	for _, item := range snapshotAfter[1].Playlist {
		if item.Media.ID == syncMedia {
			t.Errorf("sync inserted media %d into %q", syncMedia, w2.Name)
		}
	}
}

// TestLatestSyncSupersedesTheActiveOne documents the chosen overlap behaviour.
func TestLatestSyncSupersedesTheActiveOne(t *testing.T) {
	h := newHarness(t)
	ctx := context.Background()
	window := h.seedWindow(t, "Window 1", 10, 20, 30)
	first, second := window.Playlist[0].Media.ID, window.Playlist[2].Media.ID

	original := h.startSync(t, first, 60)
	h.now = original.StartAt.Add(10 * time.Second)

	replacement := h.startSync(t, second, 20)
	if replacement.ID == original.ID {
		t.Fatal("the second sync reused the first event")
	}

	live, err := h.svc.LiveSync(ctx)
	if err != nil || live == nil {
		t.Fatalf("no live sync after replacing: %v", err)
	}
	if live.ID != replacement.ID {
		t.Errorf("live sync = %d, want the replacement %d", live.ID, replacement.ID)
	}
	if live.Media.ID != second {
		t.Errorf("live media = %d, want %d", live.Media.ID, second)
	}

	// The replaced sync's original end time must no longer keep anything alive.
	h.now = replacement.EndAt.Add(time.Millisecond)
	if live, _ := h.svc.LiveSync(ctx); live != nil {
		t.Errorf("the superseded sync is still live at %s", h.now)
	}
}

// TestClientJoiningMidSyncSeesIt covers refresh/reconnect during an override:
// the client asks for the live sync and gets absolute timestamps to align to.
func TestClientJoiningMidSyncSeesIt(t *testing.T) {
	h := newHarness(t)
	ctx := context.Background()
	window := h.seedWindow(t, "Window 1", 10, 20, 30)

	event := h.startSync(t, window.Playlist[1].Media.ID, 30)
	h.now = event.StartAt.Add(12 * time.Second)

	// This is what a freshly loaded page fetches.
	snapshot, err := h.svc.Snapshot(ctx)
	if err != nil {
		t.Fatalf("snapshot: %v", err)
	}
	if snapshot.ActiveSync == nil {
		t.Fatal("a client refreshing mid-sync cannot see the active sync")
	}
	if snapshot.ActiveSync.ID != event.ID {
		t.Errorf("active sync = %d, want %d", snapshot.ActiveSync.ID, event.ID)
	}
	// Absolute timestamps let it compute the remaining time itself.
	remaining := snapshot.ActiveSync.EndAt.Sub(snapshot.ServerTime)
	if remaining != 18*time.Second {
		t.Errorf("remaining = %s, want 18s", remaining)
	}
}

func TestCancelSyncEndsTheOverrideEarly(t *testing.T) {
	h := newHarness(t)
	ctx := context.Background()
	window := h.seedWindow(t, "Window 1", 10, 20, 30)

	event := h.startSync(t, window.Playlist[0].Media.ID, 120)
	h.now = event.StartAt.Add(5 * time.Second)

	cancelled, err := h.svc.CancelSync(ctx)
	if err != nil || cancelled == nil {
		t.Fatalf("cancel: %v", err)
	}
	if live, _ := h.svc.LiveSync(ctx); live != nil {
		t.Error("the sync survived cancellation")
	}
	current, _ := h.svc.CurrentPlayback(ctx, window.ID)
	if current.SyncOverride != nil {
		t.Error("playback still reports an override after cancellation")
	}
	if h.events.CountOf(ws.EventSyncCancelled) != 1 {
		t.Errorf("expected a SYNC_CANCELLED broadcast, got %v", h.events.TypesPublished())
	}
}

func TestCancelSyncWithNothingActive(t *testing.T) {
	h := newHarness(t)
	event, err := h.svc.CancelSync(context.Background())
	if err != nil {
		t.Fatalf("cancel with no active sync should not error: %v", err)
	}
	if event != nil {
		t.Error("expected no event")
	}
}

// TestSyncEndIsAnnounced checks the convenience broadcast fires for real.
func TestSyncEndIsAnnounced(t *testing.T) {
	h := newHarness(t)
	window := h.seedWindow(t, "Window 1", 10)

	// A real (short) timer: the service schedules the announcement off the wall
	// clock, so this test uses a wall-clock-sized duration.
	h.now = time.Now().UTC()
	h.svc.now = func() time.Time { return time.Now().UTC() }
	h.svc.syncLead = 10 * time.Millisecond
	if _, err := h.svc.StartSync(context.Background(), SyncRequest{
		MediaID: window.Playlist[0].Media.ID, DurationSeconds: 1,
	}); err != nil {
		t.Fatalf("start sync: %v", err)
	}

	deadline := time.Now().Add(3 * time.Second)
	for time.Now().Before(deadline) {
		if h.events.CountOf(ws.EventSyncEnded) == 1 {
			return
		}
		time.Sleep(20 * time.Millisecond)
	}
	t.Fatalf("SYNC_ENDED was never broadcast, saw %v", h.events.TypesPublished())
}
